spring.application.name=spider-graph-api
spring.profiles.default=dev
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/openapi/spider-graph-api.yaml
server.forward-headers-strategy=framework

app.security.rate-limit.max-requests-per-minute=10
app.security.forward-headers.trust-x-forwarded-for=false
app.security.crawl.max-concurrent-requests=1
app.security.crawl.max-depth=3
app.security.crawl.max-timeout=10000
app.security.crawl.max-request-delay=2000
app.security.crawl.max-pages=50
app.security.crawl.allowed-ports=80,443
